

--
-- Procedures de atalho para ativar e desativar


CREATE OR REPLACE PROCEDURE ATIVAR_TRACE as
BEGIN

	WDS_TRACE.GERENCIAR_TRACE.ATIVAR;

END;
/




CREATE OR REPLACE PROCEDURE DESATIVAR_TRACE as
BEGIN

	WDS_TRACE.GERENCIAR_TRACE.DESATIVAR;

END;
/



CREATE OR REPLACE PROCEDURE PROCESSAR_TRACE as
BEGIN

	WDS_TRACE.EXPORTADOR_TRACE.IDENTIFICAR_NOVOS_TRACE;

END;
/



--
-- Grants 

CREATE PUBLIC SYNONYM ATIVAR_TRACE FOR WDS_TRACE.ATIVAR_TRACE;

CREATE PUBLIC SYNONYM DESATIVAR_TRACE FOR WDS_TRACE.DESATIVAR_TRACE;

CREATE PUBLIC SYNONYM PROCESSAR_TRACE FOR WDS_TRACE.PROCESSAR_TRACE;



GRANT EXECUTE ON WDS_TRACE.ATIVAR_TRACE TO PUBLIC;

GRANT EXECUTE ON WDS_TRACE.DESATIVAR_TRACE TO PUBLIC;

GRANT EXECUTE ON WDS_TRACE.PROCESSAR_TRACE TO PUBLIC;





--
-- Remover
GRANT EXECUTE ON WDS_TRACE.GERENCIAR_TRACE TO PUBLIC;
GRANT EXECUTE ON WDS_TRACE.EXPORTADOR_TRACE TO PUBLIC;

REVOKE EXECUTE ON WDS_TRACE.GERENCIAR_TRACE FROM PUBLIC;
REVOKE EXECUTE ON WDS_TRACE.EXPORTADOR_TRACE FROM PUBLIC;





GRANT EXECUTE ON WDS_TRACE.GERENCIAR_TRACE.ATIVAR TO STARTUPADMIN;
